services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  haalcentraal-personen:
      container_name: iko-haalcentraal-personen
      image: ghcr.io/brp-api/personen-mock:2.2.1
      environment:
          - ASPNETCORE_ENVIRONMENT=Release
          - ASPNETCORE_URLS=http://+:5010
      ports:
          - "5010:5010"