---
title: IKO Domain model
---
classDiagram
    note for Relation "TODO"
    note for Search "TODO"
    note for Profile "TODO"

    class Profile {
        +Id: string
        +Name: string
        +addTransformation()
        +addRole()
    }

    class Role {
        +Name: string
    }

    class Transformation {
        +JQ: string
    }

    class Search {
        +Id: string
        +Name: string
        +addTransformation()
    }

    class Relation {
        +Id: string
        +profileId: string
        +sourceId: string
        +sourceToSearchMapping: Map<string, string>
        +destinationSearchId: string
        +jqResultMapping: string
    }

    class Source {
        +Id: string
        +Name: string
        +Type: string
    }

    Profile --> "*" Transformation: applies
    Profile --> "*" Role: has
    Profile --> "1" Source: must have
    Profile --> "*" Relation: at least one
    Search --> "1" Source: one to one
    Source --> "*" Search: supports many
    Search --> "1" Transformation: applies
    Relation --> "1" Search: links

    class Profile {
        <<AggregateRoot>>
    }

    class Search {
        <<AggregateRoot>>
    }

    class Transformation {
        <<ValueObject>>
    }

    class Role {
        <<ValueObject>>
    }

    class Relation {
        <<Entity>>
    }

    class Source {
        <<Entity>>
    }