iko:
  connectors:
    openklant:
      enabled: true
      # Multi-instance configuration
      instances:
        default:
          host: https://openklant-default.example.com
          specificationUri: https://raw.githubusercontent.com/maykinmedia/open-klant/2.10.0/src/openklant/components/klantinteracties/openapi.yaml
          token: default-token-here
        instance1:
          host: https://openklant-instance1.example.com
          specificationUri: https://raw.githubusercontent.com/maykinmedia/open-klant/2.10.0/src/openklant/components/klantinteracties/openapi.yaml
          token: instance1-token-here
        instance2:
          host: https://openklant-instance2.example.com
          specificationUri: https://raw.githubusercontent.com/maykinmedia/open-klant/2.10.0/src/openklant/components/klantinteracties/openapi.yaml
          token: instance2-token-here

# Example of how to use the legacy configuration (for backward compatibility)
# iko:
#   connectors:
#     openklant:
#       enabled: true
#       host: https://openklant.example.com
#       specificationUri: https://raw.githubusercontent.com/maykinmedia/open-klant/2.10.0/src/openklant/components/klantinteracties/openapi.yaml
#       token: your-token-here