spring:
    application:
        name: IKO
    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: classpath:/templates/
    web:
        resources:
            static-locations: classpath:/static/
            cache:
                period: 0
camel:
    yaml:
        routes:
            enabled: true
            paths: classpath:camel/*.yaml

iko:
    sources:
        brp:
            enabled: true
            host: # ENV
            secret: # ENV
        openzaak:
            enabled: true
            host: # ENV
            clientId: # ENV
            secret: # ENV
        bag:
            enabled: true
            host: # ENV
            apiKey: # ENV

