### Authenticate
# @no-log
POST {{keycloak_host}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded


grant_type = password &
client_id = iko &
client_secret = ThisIsNotASecret &
username = admin &
password = admin &
scope = openid &
audience = iko