
- route:
      id: haalcentraal-route
      from:
          uri: direct:haalcentraal
          steps:

              - set-header:
                    name: Accept
                    constant: application/json

              - set-header:
                    name: Exchange.HTTP_URI
                    simple: ${header.url}

              - remove-header:
                    name: Exchange.HTTP_PATH

              - remove-header:
                    name: Exchange.HTTP_URI

              - set-body:
                    constant: >
                        {
                          "type": "RaadpleegMetBurgerservicenummer",
                          "burgerservicenummer": ["999990755"],
                          "fields": ["burgerservicenummer", "naam", "geslacht"]
                        }

              - to: haalcentraal:Personen

              - log:
                    message: 'Body before JQ: \${body}'
                    loggingLevel: INFO

              - set-body:
                    jq: |
                        {
                          burgerservicenummer: .personen[0].burgerservicenummer,
                          geslacht: {
                            omschrijving: .personen[0].geslacht.omschrijving
                          },
                          naam: {
                            aanduidingNaamgebruik: {
                              omschrijving: .personen[0].naam.aanduidingNaamgebruik.omschrijving
                            },
                            voornamen: .personen[0].naam.voornamen,
                            geslachtsnaam: .personen[0].naam.geslachtsnaam,
                            voorletters: .personen[0].naam.voorletters,
                            volledigeNaam: .personen[0].naam.volledigeNaam
                          }
                        }

              - log:
                    message: 'After JQ before marshal: \${body}'
                    loggingLevel: INFO

              - unmarshal:
                    json: {}

              - process:
                    ref: haalcentraalResponseProcessor