name: Build and Push Iko Docker image

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            image-tag: ${{ steps.build-image.outputs.IMAGE_TAG }}
        steps:
            -   uses: actions/checkout@v4
            -   id: build-image
                name: Build the Docker image
                run: |
                    TAG=iko-$(date +%s)
                    docker build . --file Dockerfile --tag iko:$TAG
                    docker save iko:$TAG -o iko-image.tar
                    echo "IMAGE_TAG=$TAG" >> "$GITHUB_OUTPUT"
            -   name: Upload tag
                uses: actions/upload-artifact@v4
                with:
                    name: iko-image-artifact
                    retention-days: 1
                    path: 'iko-image.tar'
    push:
        runs-on: ubuntu-latest
        needs:
            - build
        env:
            IMAGE_TAG: ${{needs.build.outputs.image-tag}}
        steps:
            -   name: 'Login to github packages'
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   uses: actions/download-artifact@v4
                with:
                    name: iko-image-artifact
                    path: .
            -   name: 'Prepare repository name in lowercase'
                run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
            -   run: |
                    docker load -i iko-image.tar
                    docker tag iko:$IMAGE_TAG ghcr.io/${REPO_LC}:$IMAGE_TAG
                    docker push ghcr.io/${REPO_LC}:$IMAGE_TAG
                    docker tag iko:$IMAGE_TAG ghcr.io/${REPO_LC}:latest
                    docker push ghcr.io/${REPO_LC}:latest
