name: Build and Push Snapshot Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Needed to push to GHCR and write workflow cache
permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: docker-snapshot-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }} # metadata-action lowercases it
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for optional multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Always include main tag on default branch
            type=raw,value=main,enable={{is_default_branch}}
            # Short SHA tag, e.g. sha-1a2b3c4
            type=sha,format=short,prefix=sha-
            # Snapshot date tag, e.g. snapshot-20250916
            type=raw,value=snapshot-{{date 'YYYYMMDD'}}
            # Branch tag for non-main branches (PR builds won’t push)
            type=ref,event=branch,prefix=branch-
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.created={{date 'RFC3339'}}

      - name: Build (and push on main)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # For multi-arch snapshots, uncomment next line:
          # platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
